### ISSUE TITLE
vue引入插件--上传demo中的init.js报错UploadClient is not defined

### ISSUE THREAD

**Issue by lmfuture** [rongcloud/rongcloud-web-im-upload#4]
请问是什么原因呢，有点着急。。。谢谢了

**Comment by YongHao0** [comment]
您看以下思路排查下:
1. Web 站点必须为 https 或 http, 不建议使用 file:// 访问
2. 建议您使用 qiniu/message.html 进行参考校验, 此 Demo 包含获取 token、上传、获取 url 的全部流程
更多问题您可提交工单: https://developer.rongcloud.cn/ticket/create
